# run: conda env create -f environment.yml
name: srs-game
channels:
  - anaconda
  - newville     # wxpython-phoenix
  - conda-forge
dependencies:
  - python=3
  - python.app   # pythonw, for wx
  - wxpython-phoenix
  - pyinstaller
  - pip:
    - transcrypt
